### ISSUE TITLE
Добавить ссылку на демо страницы

### ISSUE THREAD

**Issue by tsvetkovamaria** [tosyak/html_group_8_homework_34_vitali_danichkin#11]
Для облегчения просмотра вашей страницы, было бы здорово добавить сылку на уже свертсанную страницу (демо) в файл readme.md вашего репозитория (и сам файл тоже). Тогда любой человек сможет зайтив репо, кликнуть на ссылку и посмотреть готовую работу в браузере, не клонируя репо локально. 

Можно добавить себе демо версию страницы через github pages

**Comment by tosyak** [comment]
добавил.
